import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import { readFile, mkdir, stat } from 'node:fs/promises';
import path from 'node:path';
import { createTestProfile } from './test-profile.mjs';

const samples = JSON.parse(await readFile('detector/tests/fixtures/samples.json', 'utf8'));
const defaults = JSON.parse(await readFile('shared/settings-defaults.json', 'utf8'));
const profile = await createTestProfile('settings');
const env = { ...process.env, HF_HUB_OFFLINE: '1' };
delete env.ELECTRON_RUN_AS_NODE; delete env.PROOFGPT_DEV_URL;
const launch = () => electron.launch({ args: ['.', `--user-data-dir=${profile}`], env });
let app, page;
const errors = [];
const go = (name) => page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name, exact: true }).click();
const currentSettings = async () => (await page.evaluate(() => window.desktop.settings.get())).settings;
const history = async () => (await page.evaluate(() => window.desktop.history.list())).records;
async function toggle(name, desired) {
  const control = page.getByRole('switch', { name, exact: true });
  if ((await control.getAttribute('aria-checked')) !== String(desired)) await control.click();
  await page.waitForFunction(({ name, desired }) => {
    const control = [...document.querySelectorAll('[role="switch"]')].find((element) => document.getElementById(element.getAttribute('aria-labelledby'))?.textContent === name);
    return control?.getAttribute('aria-checked') === String(desired) && !control.disabled;
  }, { name, desired });
}
async function select(name, value) {
  await page.getByRole('combobox', { name, exact: true }).selectOption(value);
  await page.waitForFunction(({ name, value }) => {
    const control = [...document.querySelectorAll('select')].find((element) => document.getElementById(element.getAttribute('aria-labelledby'))?.textContent === name);
    return control?.value === value && !control.disabled;
  }, { name, value });
}
async function analyze(sample, testResetGuard = false) {
  await go('Home');
  await page.getByRole('textbox', { name: 'Text to analyze' }).fill(sample.text);
  await page.getByRole('button', { name: 'Analyze Text', exact: true }).click();
  await page.getByRole('button', { name: 'Analyzing...', exact: true }).waitFor();
  if (testResetGuard) {
    const response = await page.evaluate(() => window.desktop.settings.resetData());
    assert.equal(response.ok, false); assert.match(response.error, /current analysis/);
  }
  await page.getByRole('heading', { name: 'Analysis result', exact: true }).waitFor();
  return Number((await page.locator('.analyzer').getByTestId('ai-score').innerText()).replace('%', ''));
}
async function confirmAction(name) {
  await page.getByRole('button', { name, exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name, exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'detached' });
}
try {
  app = await launch(); page = await app.firstWindow(); page.setDefaultTimeout(180000);
  page.on('pageerror', (error) => errors.push(error.message));
  await page.getByRole('heading', { name: 'Detect AI-Generated Text' }).waitFor();
  assert.deepEqual(await currentSettings(), defaults);
  await go('Settings');
  assert.equal(await page.locator('[aria-current="page"]').innerText(), 'Settings');
  assert.equal(await page.getByTestId('app-version').innerText(), await app.evaluate(({ app }) => app.getVersion()));
  assert.equal(await page.getByRole('combobox', { name: 'Language', exact: true }).locator('option').count(), 1);
  assert.equal(await page.locator('.settings-dark-theme').innerText(), 'Dark');
  assert.equal(await page.getByRole('button', { name: /Upgrade|Sign Out/ }).count(), 0);
  await mkdir('artifacts', { recursive: true });
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1536, 1024));
  await page.screenshot({ path: 'artifacts/settings-desktop.png' });
  await select('Analysis detail level', 'detailed');
  await toggle('Include Explanations', false);
  await toggle('Short text warning', false);
  await select('Start-up', 'settings');
  await go('Home');
  await page.getByRole('textbox', { name: 'Text to analyze' }).fill('Too short.');
  await page.getByRole('button', { name: 'Analyze Text', exact: true }).click();
  assert.match(await page.getByRole('alert').innerText(), /at least 50 words/);
  await page.getByRole('textbox', { name: 'Text to analyze' }).fill('word '.repeat(60));
  assert.equal(await page.locator('.analysis-short-warning').count(), 0);
  const aiScore = await analyze(samples[0], true);
  assert.equal(await page.locator('.analysis-detailed-info tbody tr').count(), 1);
  assert.equal(await page.getByRole('heading', { name: 'Why ProofGPT gave this result' }).count(), 0);
  assert.equal((await history()).length, 1);
  await go('Settings');
  assert.equal(await page.getByRole('combobox', { name: 'Analysis detail level' }).inputValue(), 'detailed');
  await toggle('Save analyses to History', false);
  assert.equal((await history()).length, 1); // Existing records are retained.
  const humanScore = await analyze(samples[2]);
  assert.notEqual(humanScore, aiScore);
  assert.match(await page.locator('.analyzer .result-note').last().innerText(), /not saved.*saving is off/);
  assert.equal((await history()).length, 1);
  await go('Reports');
  await page.getByTestId('report-total').waitFor();
  assert.equal(await page.getByTestId('report-total').innerText(), '1');
  assert.equal(await page.getByTestId('report-average').innerText(), `${aiScore}%`);
  await go('Settings');
  await select('Default export format', 'json');
  await toggle('Include chart data in JSON', false);
  await go('Reports');
  const exportFile = path.join(profile, 'preferred-export.json');
  await app.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async (_window, options) => { globalThis.exportOptions = options; return { canceled: false, filePath: file }; }; }, exportFile);
  await page.getByRole('button', { name: /^Export JSON:/ }).first().click();
  await page.getByRole('status').filter({ hasText: 'Report saved' }).waitFor();
  const exported = JSON.parse(await readFile(exportFile, 'utf8'));
  assert.equal(exported.analyses[0].text, samples[0].text);
  assert.equal(exported.trend, undefined); assert.equal(exported.summary.distribution, undefined);
  assert.match(await app.evaluate(() => globalThis.exportOptions.defaultPath), /\.json$/);
  await app.close(); app = undefined;
  app = await launch(); page = await app.firstWindow(); page.setDefaultTimeout(180000);
  page.on('pageerror', (error) => errors.push(error.message));
  await page.getByRole('heading', { name: 'Settings', exact: true }).waitFor();
  const persisted = await currentSettings();
  assert.equal(persisted.startPage, 'settings'); assert.equal(persisted.saveHistory, false);
  assert.equal(persisted.detailLevel, 'detailed'); assert.equal(persisted.includeExplanations, false);
  assert.equal(persisted.defaultExportFormat, 'json'); assert.equal(persisted.includeChartData, false);
  assert.deepEqual(JSON.parse(await readFile(path.join(profile, 'settings.json'), 'utf8')).settings, persisted);
  await toggle('Short text warning', true);
  await go('Home');
  await page.getByRole('textbox', { name: 'Text to analyze' }).fill('word '.repeat(60));
  await page.locator('.analysis-short-warning').waitFor();
  assert.equal(await page.getByRole('button', { name: 'Analyze Text', exact: true }).isEnabled(), true);
  await go('Settings');
  // Native button keyboard activation switches the persistent toggle.
  await page.getByRole('switch', { name: 'Save analyses to History' }).focus();
  await page.getByRole('switch', { name: 'Save analyses to History' }).press('Space');
  await page.waitForFunction(() => document.querySelector('[aria-labelledby="save-history-label"]').getAttribute('aria-checked') === 'true');
  const savedHumanScore = await analyze(samples[2]);
  assert.equal(savedHumanScore, humanScore);
  assert.equal((await history()).length, 2);
  assert.ok((await history()).some((record) => record.text === samples[2].text));
  await go('Settings');
  await page.getByRole('button', { name: 'Restore Defaults', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel' }).click();
  assert.equal((await currentSettings()).defaultExportFormat, 'json');
  await confirmAction('Restore Defaults');
  assert.deepEqual(await currentSettings(), defaults);
  assert.equal((await history()).length, 2);
  await go('Home');
  assert.equal(await page.locator('.analysis-detailed-info').count(), 0);
  await page.getByRole('heading', { name: 'Why ProofGPT gave this result' }).waitFor();
  assert.equal(await page.locator('.analyzer').getByTestId('ai-score').innerText(), `${savedHumanScore}%`);
  await go('Reports');
  assert.equal(await page.getByTestId('report-total').innerText(), '2');
  assert.equal(await page.getByRole('button', { name: /^Export CSV:/ }).count(), 2);
  const chartExport = path.join(profile, 'with-charts.json');
  await app.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }); }, chartExport);
  await page.getByRole('button', { name: 'Export JSON', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Report saved' }).waitFor();
  assert.equal(JSON.parse(await readFile(chartExport, 'utf8')).trend.length, 2);
  await go('Settings');
  await page.getByRole('button', { name: 'Clear History', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel' }).click();
  assert.equal((await history()).length, 2);
  await confirmAction('Clear History');
  assert.deepEqual(await history(), []);
  await go('Reports');
  await page.getByRole('heading', { name: 'No report data yet' }).waitFor();
  await analyze(samples[2]);
  const record = (await history())[0];
  const modelConfig = path.join('.model-cache', 'hub', 'models--ShantanuT01--dactyl-ai-text-detector', 'snapshots', record.modelRevision, 'config.json');
  const modelBeforeReset = await readFile(modelConfig, 'utf8');
  await go('Settings');
  await select('Default export format', 'json');
  await toggle('Save analyses to History', false);
  await page.getByRole('button', { name: 'Reset ProofGPT Data', exact: true }).click();
  const dialog = page.getByRole('dialog');
  assert.equal(await dialog.getByRole('button', { name: 'Reset ProofGPT Data', exact: true }).isDisabled(), true);
  await dialog.getByRole('textbox', { name: 'Type RESET to confirm' }).fill('reset');
  assert.equal(await dialog.getByRole('button', { name: 'Reset ProofGPT Data', exact: true }).isDisabled(), true);
  await dialog.getByRole('button', { name: 'Cancel' }).click();
  assert.equal((await history()).length, 1);
  await page.getByRole('button', { name: 'Reset ProofGPT Data', exact: true }).click();
  await dialog.getByRole('textbox', { name: 'Type RESET to confirm' }).fill('RESET');
  await dialog.getByRole('button', { name: 'Reset ProofGPT Data', exact: true }).click();
  await dialog.waitFor({ state: 'detached' });
  assert.deepEqual(await currentSettings(), defaults); assert.deepEqual(await history(), []);
  assert.equal(await readFile(modelConfig, 'utf8'), modelBeforeReset);
  assert.ok((await stat(exportFile)).size > 0);
  await go('Home');
  assert.equal(await page.getByRole('textbox', { name: 'Text to analyze' }).inputValue(), '');
  assert.equal(await page.locator('.analysis-result').count(), 0);
  await go('Reports'); await page.getByRole('heading', { name: 'No report data yet' }).waitFor();
  await go('History'); await page.getByRole('heading', { name: 'No analyses yet' }).waitFor();
  await app.close(); app = undefined;
  env.PROOFGPT_PYTHON = 'C:/ProofGPT-test-missing/python.exe';
  app = await launch(); page = await app.firstWindow();
  page.on('pageerror', (error) => errors.push(error.message));
  await page.getByRole('heading', { name: 'Detect AI-Generated Text' }).waitFor();
  assert.deepEqual(await currentSettings(), defaults);
  await go('Settings');
  const unsupported = await page.evaluate(() => window.desktop.settings.update({ theme: 'light' }));
  assert.equal(unsupported.ok, false);
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(850, 660));
  await page.waitForTimeout(100);
  assert.equal(await page.locator('.settings-page').evaluate((element) => element.scrollWidth > element.clientWidth), false);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: 'artifacts/settings-compact.png' });
  assert.deepEqual(errors, []);
  console.log('PASS: Settings navigation, immediate detail/explanation/warnings, mandatory word minimum, persistence/startup, real unsaved/saved inference, export defaults/data preference, clear/cancel and Reports updates, defaults retain History, typed reset clears memory/data but keeps model/exports, reset blocked during analysis, keyboard, minimum resize, no renderer errors.');
} finally { await app?.close(); }
